baseURL = "https://mypam.com/"
languageCode = "en"
title = "The software to manage your workspaces"
DefaultContentLanguage = "en"
[languages]
    [languages.en]
        LanguageName = "English"
        title = "The software to manage your workspaces"
    [languages.de]
        LanguageName = "Deutsch"
        title = "Die Software zur Verwaltung Ihrer Arbeitsbereiche"
    [languages.es]
        LanguageName = "Espa√±ol"
        title = "El software para administrar sus espacios de trabajo"
[outputFormats]
    [outputFormats.SearchIndex]
        baseName = "search"
        mediatype = "application/json"
[outputs]
    section = ["JSON", "HTML", "SearchIndex"]
